tta:
  name: submission
  class_path: tta.submission.Submission
  args:
    episodic: false
    optim_steps: 2
    optim_lr: 0.0001
    optim_method: Adam
    optim_beta: 0.9
    optim_momentum: 0.9
    optim_dampening: 0.0
    optim_nesterov: true
    optim_wd: 0.0

evaluation:
  batch_size: 512
