tta:
  name: submission
  class_path: tta.submission.Submission
  args:
    norm_eps: 1.0e-5
    norm_momentum: 0.1
    optim_steps: 2
    optim_lr: 0.0001
    optim_method: Adam
    optim_beta: 0.9
    optim_momentum: 0.9
    optim_dampening: 0.0
    optim_nesterov: true
    optim_wd: 0.0
    norm_batch_size: 1024
    tent_batch_size: 512

evaluation:
  batch_size: 10000
